services:
  loki:
    image: grafana/loki:3.4.1
    volumes:
      - ./loki-config.yaml:/mnt/config/loki-config.yaml
    command: -config.file=/mnt/config/loki-config.yaml
    networks:
      - dokploy-network
    healthcheck:
      test: ["CMD", "curl", "http://localhost:3100/ready"]
      interval: 30s
      timeout: 10s
      retries: 3
  nginx:
    container_name: loki.nginx
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - LOKI_USER=admin
      - LOKI_PASS=sjwu@23Nni
    volumes:
      - ./loki.conf:/etc/nginx/conf.d/default.conf
    networks:
      - dokploy-network
    depends_on:
      - loki
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/ready"]
      interval: 30s
      timeout: 10s
      retries: 3
  grafana:
   image: grafana/grafana:latest
   depends_on:
     - nginx
   networks:
     - dokploy-network

networks:
  dokploy-network:
    name: dokploy-network
    external: true
