services:
  loki:
    image: grafana/loki:3.4.1
    volumes:
      - ./loki-config.yaml:/mnt/config/loki-config.yaml
    command: -config.file=/mnt/config/loki-config.yaml
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - LOKI_USER=admin
      - LOKI_PASS=sjwu@23Nni
    volumes:
      - ./loki.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - loki
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/ready"]
      interval: 30s
      timeout: 10s
      retries: 3